name: Ejecutar Script Hola Mundo

# 1. El Evento (Trigger)
on:
  push:
    branches:
      - main

# 2. Los Trabajos (Jobs)
jobs:
  correr-script:
    # 3. El entorno (Runner)
    runs-on: ubuntu-latest

    # 4. Los pasos a seguir (Steps)
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java en el servidor
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar y ejecutar el script
        run: |
          javac HolaMundo.java
          java HolaMundo
